<?php
declare(strict_types=1);

namespace Mnemesong\Structure\collections;

use Mnemesong\Structure\StructureInterface;
use Webmozart\Assert\Assert;

/**
 * Collection of StructureInterfaces.
 *
 * Generated by: mnemesong\collection-generator v.0.4
 */
final class StructureInterfaceCollection implements \Countable, \JsonSerializable
{
    /* @var \Mnemesong\Structure\StructureInterface[] $objects */
    /* @phpstan-ignore-next-line  */
    protected array $objects = [];

    /**
     * @param StructureInterface[] $objects
     */
    public function __construct(array $objects = [])
    {
        Assert::allIsInstanceOf($objects, StructureInterface::class);
        $this->objects = array_values($objects);
    }

    /**
     * @param \Mnemesong\Structure\StructureInterface $object
     * @return self
     */
    public function withNewOneItem(StructureInterface $object): self
    {
        Assert::isInstanceOf($object, StructureInterface::class,
            "Added items should be instance of StructureInterface");
        $clone = clone $this;
        $clone->objects[] = $object;
        return $clone;
    }

    /**
     * @param \Mnemesong\Structure\StructureInterface[] $objects
     * @return self
     */
    public function withManyNewItems(array $objects): self
    {
        Assert::allIsInstanceOf($objects, StructureInterface::class);
        $clone = clone $this;
        $clone->objects = array_merge($clone->objects, array_values($objects));
        return $clone;
    }

    /**
     * @return StructureInterface[]
     */
    public function getAll(): array
    {
        return $this->objects;
    }

    /**
     * @param \Mnemesong\Structure\StructureInterface $object
     * @return int|null
     */
    protected function getIndex(StructureInterface $object): ?int
    {
        $filtered = array_filter($this->objects, function (StructureInterface $innerObject) use ($object) {
            return $innerObject == $object;
        });
        if(count($filtered) > 0) {
            return current(array_keys($filtered));
        }
        return null;
    }

    /**
     * @param \Mnemesong\Structure\StructureInterface $object
     * @return int[]
     */
    protected function getAllIndexes(StructureInterface $object): array
    {
        $filtered = array_filter($this->objects, function (StructureInterface $innerObject) use ($object) {
            return $innerObject == $object;
        });
        return array_keys($filtered);
    }

    /**
     * @param \Mnemesong\Structure\StructureInterface $object
     * @param int $limit
     * @return self
     */
    public function withoutObjectsLike(StructureInterface $object, int $limit = 0): self
    {
        $arr = $this->objects;
        $i = $limit;
        if($limit < 0) {
            $arr = array_reverse($arr);
            $i = -$limit;
        }
        $newArr = [];
        foreach ($arr as $item)
        {
            if($limit !== 0) {
                if($item != $object)  {
                    $newArr[] = $item;
                } else {
                    if($i > 0) {
                        $i--;
                    } else {
                        $newArr[] = $item;
                    }
                }
            } else {
                if($item != $object)  {
                    $newArr[] = $item;
                }
            }
        }
        if($limit < 0) {
            $newArr = array_reverse($newArr);
        }
        return new self($newArr);
    }

    /**
     * @param callable $callbackFunction
     * @return self
     */
    public function filteredBy(callable $callbackFunction): self
    {
        $clone = clone $this;
        $clone->objects = array_values(array_filter($clone->objects, $callbackFunction));
        return $clone;
    }

    /**
     * @param callable $callbackFunction
     * @return array
     */
    /* @phpstan-ignore-next-line  */
    public function map(callable $callbackFunction): array
    {
        return array_map($callbackFunction, $this->objects);
    }

    /**
     * @param callable $callbackFunction
     * @return self
     * @throws \ErrorException
     */
    public function reworkedBy(callable $callbackFunction): self
    {
        $newArray = array_map($callbackFunction, $this->objects);
        $checkFilter = array_filter($newArray, function ($item) {
            return !is_a($item, StructureInterface::class);
        });
        if(!empty($checkFilter)) {
            throw new \ErrorException('Wrong type result at Apply() method execution in collection ' . self::class);
        }
        $clone = clone $this;
        $clone->objects = $newArray;
        return $clone;
    }

    /**
     * @return int
     */
    public function count(): int
    {
        return count($this->objects);
    }

    /**
     * @return \Mnemesong\Structure\StructureInterface[]
     */
    public function jsonSerialize(): array
    {
        return $this->objects;
    }

    /**
     * @return \Mnemesong\Structure\StructureInterface
     */
    public function getFirstAsserted(): StructureInterface
    {
        if($this->count() === 0) {
            throw new \RuntimeException('Error: try to get first element from empty StructureInterfaces collection');
        }
        return $this->objects[array_key_first($this->objects)];
    }

    /**
     * @return \Mnemesong\Structure\StructureInterface
     */
    public function getLastAsserted(): StructureInterface
    {
        if($this->count() === 0) {
            throw new \RuntimeException('Error: try to get last element from empty StructureInterfaces collection');
        }
        return $this->objects[array_key_last($this->objects)];
    }

    /**
     * @param callable $func
     * @return self
     */
    public function assertCount(callable $func): self
    {
        if($func($this->count()) !== true) {
            throw new \AssertionError('Count assert error');
        }
        return $this;
    }

    /**
     * @return \Mnemesong\Structure\StructureInterface|null
     */
    public function getFirstOrNull(): ?StructureInterface
    {
        if($this->count() > 0) {
            return $this->getFirstAsserted();
        }
        return null;
    }

    /**
     * @return \Mnemesong\Structure\StructureInterface|null
     */
    public function getLastOrNull(): ?StructureInterface
    {
        if($this->count() > 0) {
            return $this->getLastAsserted();
        }
        return null;
    }

    /**
     * @param callable $sortFunc
     * @return $this
     * @throws \ErrorException
     */
    public function sortedBy(callable $sortFunc): self
    {
        $clone = clone $this;
        if(uasort($clone->objects, $sortFunc) === false) {
            throw new \ErrorException('Error while resorting collection');
        }
        $clone->objects = array_values($clone->objects);
        return $clone;
    }

}